root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/api"
  bin = "./tmp/main"
  full_bin = "./tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", ".git", "internal/db/migrations"]
  delay = 1000

[log]
  time = true

[misc]
  clean_on_exit = true