// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer_addresses.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAddressesByUser = `-- name: CountAddressesByUser :one
SELECT count(*) FROM customer_addresses WHERE user_id = $1
`

func (q *Queries) CountAddressesByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAddressesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomerAddress = `-- name: CreateCustomerAddress :one
INSERT INTO customer_addresses (user_id, label, address, location, delivery_note, is_default)
VALUES (
    $1, $2, $3,
    ST_SetSRID(ST_MakePoint($4::float8, $5::float8), 4326)::geography,
    $6, $7
)
RETURNING
    id, user_id, label, address,
    ST_Y(location::geometry)::float8 AS lat,
    ST_X(location::geometry)::float8 AS lng,
    delivery_note, is_default, created_at, updated_at
`

type CreateCustomerAddressParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Label        string    `json:"label"`
	Address      string    `json:"address"`
	Lng          float64   `json:"lng"`
	Lat          float64   `json:"lat"`
	DeliveryNote *string   `json:"delivery_note"`
	IsDefault    bool      `json:"is_default"`
}

type CreateCustomerAddressRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Label        string             `json:"label"`
	Address      string             `json:"address"`
	Lat          float64            `json:"lat"`
	Lng          float64            `json:"lng"`
	DeliveryNote *string            `json:"delivery_note"`
	IsDefault    bool               `json:"is_default"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCustomerAddress(ctx context.Context, arg CreateCustomerAddressParams) (CreateCustomerAddressRow, error) {
	row := q.db.QueryRow(ctx, createCustomerAddress,
		arg.UserID,
		arg.Label,
		arg.Address,
		arg.Lng,
		arg.Lat,
		arg.DeliveryNote,
		arg.IsDefault,
	)
	var i CreateCustomerAddressRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.DeliveryNote,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomerAddress = `-- name: DeleteCustomerAddress :exec
DELETE FROM customer_addresses
WHERE id = $1 AND user_id = $2
`

type DeleteCustomerAddressParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteCustomerAddress(ctx context.Context, arg DeleteCustomerAddressParams) error {
	_, err := q.db.Exec(ctx, deleteCustomerAddress, arg.ID, arg.UserID)
	return err
}

const getCustomerAddressByID = `-- name: GetCustomerAddressByID :one
SELECT
    id, user_id, label, address,
    ST_Y(location::geometry)::float8 AS lat,
    ST_X(location::geometry)::float8 AS lng,
    delivery_note, is_default, created_at, updated_at
FROM customer_addresses
WHERE id = $1 AND user_id = $2
`

type GetCustomerAddressByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetCustomerAddressByIDRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Label        string             `json:"label"`
	Address      string             `json:"address"`
	Lat          float64            `json:"lat"`
	Lng          float64            `json:"lng"`
	DeliveryNote *string            `json:"delivery_note"`
	IsDefault    bool               `json:"is_default"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCustomerAddressByID(ctx context.Context, arg GetCustomerAddressByIDParams) (GetCustomerAddressByIDRow, error) {
	row := q.db.QueryRow(ctx, getCustomerAddressByID, arg.ID, arg.UserID)
	var i GetCustomerAddressByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.DeliveryNote,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomerAddressesByUser = `-- name: ListCustomerAddressesByUser :many
SELECT
    id, user_id, label, address,
    ST_Y(location::geometry)::float8 AS lat,
    ST_X(location::geometry)::float8 AS lng,
    delivery_note, is_default, created_at, updated_at
FROM customer_addresses
WHERE user_id = $1
ORDER BY is_default DESC, created_at DESC
`

type ListCustomerAddressesByUserRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Label        string             `json:"label"`
	Address      string             `json:"address"`
	Lat          float64            `json:"lat"`
	Lng          float64            `json:"lng"`
	DeliveryNote *string            `json:"delivery_note"`
	IsDefault    bool               `json:"is_default"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCustomerAddressesByUser(ctx context.Context, userID uuid.UUID) ([]ListCustomerAddressesByUserRow, error) {
	rows, err := q.db.Query(ctx, listCustomerAddressesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerAddressesByUserRow
	for rows.Next() {
		var i ListCustomerAddressesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.DeliveryNote,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsetDefaultAddressForUser = `-- name: UnsetDefaultAddressForUser :exec
UPDATE customer_addresses
SET is_default = false, updated_at = now()
WHERE user_id = $1 AND is_default = true
`

func (q *Queries) UnsetDefaultAddressForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, unsetDefaultAddressForUser, userID)
	return err
}

const updateCustomerAddress = `-- name: UpdateCustomerAddress :one
UPDATE customer_addresses
SET
    label = $1, address = $2,
    location = ST_SetSRID(ST_MakePoint($3::float8, $4::float8), 4326)::geography,
    delivery_note = $5, is_default = $6,
    updated_at = now()
WHERE id = $7 AND user_id = $8
RETURNING
    id, user_id, label, address,
    ST_Y(location::geometry)::float8 AS lat,
    ST_X(location::geometry)::float8 AS lng,
    delivery_note, is_default, created_at, updated_at
`

type UpdateCustomerAddressParams struct {
	Label        string    `json:"label"`
	Address      string    `json:"address"`
	Lng          float64   `json:"lng"`
	Lat          float64   `json:"lat"`
	DeliveryNote *string   `json:"delivery_note"`
	IsDefault    bool      `json:"is_default"`
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
}

type UpdateCustomerAddressRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Label        string             `json:"label"`
	Address      string             `json:"address"`
	Lat          float64            `json:"lat"`
	Lng          float64            `json:"lng"`
	DeliveryNote *string            `json:"delivery_note"`
	IsDefault    bool               `json:"is_default"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateCustomerAddress(ctx context.Context, arg UpdateCustomerAddressParams) (UpdateCustomerAddressRow, error) {
	row := q.db.QueryRow(ctx, updateCustomerAddress,
		arg.Label,
		arg.Address,
		arg.Lng,
		arg.Lat,
		arg.DeliveryNote,
		arg.IsDefault,
		arg.ID,
		arg.UserID,
	)
	var i UpdateCustomerAddressRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.DeliveryNote,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
