// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppRole string

const (
	AppRoleCustomer   AppRole = "customer"
	AppRoleRider      AppRole = "rider"
	AppRoleStoreOwner AppRole = "store_owner"
	AppRoleAdmin      AppRole = "admin"
)

func (e *AppRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppRole(s)
	case string:
		*e = AppRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AppRole: %T", src)
	}
	return nil
}

type NullAppRole struct {
	AppRole AppRole `json:"app_role"`
	Valid   bool    `json:"valid"` // Valid is true if AppRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppRole) Scan(value interface{}) error {
	if value == nil {
		ns.AppRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppRole), nil
}

type DevicePlatform string

const (
	DevicePlatformIos     DevicePlatform = "ios"
	DevicePlatformAndroid DevicePlatform = "android"
	DevicePlatformWeb     DevicePlatform = "web"
)

func (e *DevicePlatform) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DevicePlatform(s)
	case string:
		*e = DevicePlatform(s)
	default:
		return fmt.Errorf("unsupported scan type for DevicePlatform: %T", src)
	}
	return nil
}

type NullDevicePlatform struct {
	DevicePlatform DevicePlatform `json:"device_platform"`
	Valid          bool           `json:"valid"` // Valid is true if DevicePlatform is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDevicePlatform) Scan(value interface{}) error {
	if value == nil {
		ns.DevicePlatform, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DevicePlatform.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDevicePlatform) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DevicePlatform), nil
}

type RiderStatus string

const (
	RiderStatusOffline    RiderStatus = "offline"
	RiderStatusOnline     RiderStatus = "online"
	RiderStatusOnDelivery RiderStatus = "on_delivery"
)

func (e *RiderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiderStatus(s)
	case string:
		*e = RiderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RiderStatus: %T", src)
	}
	return nil
}

type NullRiderStatus struct {
	RiderStatus RiderStatus `json:"rider_status"`
	Valid       bool        `json:"valid"` // Valid is true if RiderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RiderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiderStatus), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
	UserStatusDeleted   UserStatus = "deleted"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AuthUser struct {
	ID uuid.UUID `json:"id"`
}

type CustomerAddress struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Label        string             `json:"label"`
	Address      string             `json:"address"`
	Location     interface{}        `json:"location"`
	DeliveryNote *string            `json:"delivery_note"`
	IsDefault    bool               `json:"is_default"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type FcmDeviceToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	Platform  DevicePlatform     `json:"platform"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Type        string             `json:"type"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	ImageUrl    *string            `json:"image_url"`
	IsRead      bool               `json:"is_read"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Rider struct {
	UserID          uuid.UUID          `json:"user_id"`
	Status          RiderStatus        `json:"status"`
	IsAvailable     bool               `json:"is_available"`
	AssignedArea    *string            `json:"assigned_area"`
	CurrentLocation interface{}        `json:"current_location"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Phone     *string            `json:"phone"`
	Status    UserStatus         `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type UserProfile struct {
	UserID          uuid.UUID          `json:"user_id"`
	FirstName       *string            `json:"first_name"`
	LastName        *string            `json:"last_name"`
	ProfileImageUrl *string            `json:"profile_image_url"`
	BirthDate       pgtype.Date        `json:"birth_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UserRole struct {
	UserID uuid.UUID `json:"user_id"`
	Role   AppRole   `json:"role"`
}
