// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountAddressesByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateCustomerAddress(ctx context.Context, arg CreateCustomerAddressParams) (CreateCustomerAddressRow, error)
	// =============================================================================
	// NOTIFICATIONS (1:many with users)
	// =============================================================================
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	DeleteCustomerAddress(ctx context.Context, arg DeleteCustomerAddressParams) error
	DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error
	GetCustomerAddressByID(ctx context.Context, arg GetCustomerAddressByIDParams) (GetCustomerAddressByIDRow, error)
	// =============================================================================
	// RIDERS (1:1 with users)
	// =============================================================================
	GetRiderByUserID(ctx context.Context, userID uuid.UUID) (GetRiderByUserIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// =============================================================================
	// USERS
	// =============================================================================
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// =============================================================================
	// USER PROFILES (1:1 with users)
	// =============================================================================
	GetUserProfile(ctx context.Context, userID uuid.UUID) (UserProfile, error)
	// =============================================================================
	// USER ROLES (1:1 with users)
	// =============================================================================
	GetUserRole(ctx context.Context, userID uuid.UUID) (UserRole, error)
	GetUserWithProfile(ctx context.Context, id uuid.UUID) (GetUserWithProfileRow, error)
	ListAvailableRidersNearby(ctx context.Context, arg ListAvailableRidersNearbyParams) ([]ListAvailableRidersNearbyRow, error)
	ListCustomerAddressesByUser(ctx context.Context, userID uuid.UUID) ([]ListCustomerAddressesByUserRow, error)
	ListDeviceTokensByUser(ctx context.Context, userID uuid.UUID) ([]FcmDeviceToken, error)
	ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]User, error)
	MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	SetUserRole(ctx context.Context, arg SetUserRoleParams) (UserRole, error)
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UnsetDefaultAddressForUser(ctx context.Context, userID uuid.UUID) error
	UpdateCustomerAddress(ctx context.Context, arg UpdateCustomerAddressParams) (UpdateCustomerAddressRow, error)
	UpdateRiderLocation(ctx context.Context, arg UpdateRiderLocationParams) error
	UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) (User, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
	// =============================================================================
	// FCM DEVICE TOKENS (1:many with users)
	// =============================================================================
	UpsertFCMDeviceToken(ctx context.Context, arg UpsertFCMDeviceTokenParams) (FcmDeviceToken, error)
	UpsertRider(ctx context.Context, arg UpsertRiderParams) (UpsertRiderRow, error)
	UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error)
}

var _ Querier = (*Queries)(nil)
