// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (user_id, type, title, description, image_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, title, description, image_url, is_read, created_at
`

type CreateNotificationParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Type        string    `json:"type"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	ImageUrl    *string   `json:"image_url"`
}

// =============================================================================
// NOTIFICATIONS (1:many with users)
// =============================================================================
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.ImageUrl,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM fcm_device_tokens
WHERE token = $1 AND user_id = $2
`

type DeleteDeviceTokenParams struct {
	Token  string    `json:"token"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, arg.Token, arg.UserID)
	return err
}

const getRiderByUserID = `-- name: GetRiderByUserID :one

SELECT
    user_id, status, is_available, assigned_area,
    ST_Y(current_location::geometry) AS lat,
    ST_X(current_location::geometry) AS lng,
    updated_at
FROM riders
WHERE user_id = $1
`

type GetRiderByUserIDRow struct {
	UserID       uuid.UUID          `json:"user_id"`
	Status       RiderStatus        `json:"status"`
	IsAvailable  bool               `json:"is_available"`
	AssignedArea *string            `json:"assigned_area"`
	Lat          interface{}        `json:"lat"`
	Lng          interface{}        `json:"lng"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// =============================================================================
// RIDERS (1:1 with users)
// =============================================================================
func (q *Queries) GetRiderByUserID(ctx context.Context, userID uuid.UUID) (GetRiderByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getRiderByUserID, userID)
	var i GetRiderByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.IsAvailable,
		&i.AssignedArea,
		&i.Lat,
		&i.Lng,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, phone, status, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, email, phone, status, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

// =============================================================================
// USERS
// =============================================================================
func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one

SELECT user_id, first_name, last_name, profile_image_url, birth_date, created_at, updated_at FROM user_profiles
WHERE user_id = $1
`

// =============================================================================
// USER PROFILES (1:1 with users)
// =============================================================================
func (q *Queries) GetUserProfile(ctx context.Context, userID uuid.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.ProfileImageUrl,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one

SELECT user_id, role FROM user_roles
WHERE user_id = $1
`

// =============================================================================
// USER ROLES (1:1 with users)
// =============================================================================
func (q *Queries) GetUserRole(ctx context.Context, userID uuid.UUID) (UserRole, error) {
	row := q.db.QueryRow(ctx, getUserRole, userID)
	var i UserRole
	err := row.Scan(&i.UserID, &i.Role)
	return i, err
}

const getUserWithProfile = `-- name: GetUserWithProfile :one
SELECT
    u.id, u.email, u.phone, u.status, u.created_at, u.updated_at,
    p.first_name, p.last_name, p.profile_image_url, p.birth_date
FROM users u
LEFT JOIN user_profiles p ON p.user_id = u.id
WHERE u.id = $1 AND u.deleted_at IS NULL
`

type GetUserWithProfileRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	Phone           *string            `json:"phone"`
	Status          UserStatus         `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	FirstName       *string            `json:"first_name"`
	LastName        *string            `json:"last_name"`
	ProfileImageUrl *string            `json:"profile_image_url"`
	BirthDate       pgtype.Date        `json:"birth_date"`
}

func (q *Queries) GetUserWithProfile(ctx context.Context, id uuid.UUID) (GetUserWithProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserWithProfile, id)
	var i GetUserWithProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.ProfileImageUrl,
		&i.BirthDate,
	)
	return i, err
}

const listAvailableRidersNearby = `-- name: ListAvailableRidersNearby :many
SELECT
    user_id, status, is_available, assigned_area,
    ST_Y(current_location::geometry) AS lat,
    ST_X(current_location::geometry) AS lng,
    ST_Distance(current_location, ST_SetSRID(ST_MakePoint($2::float8, $3::float8), 4326)::geography) AS distance_meters
FROM riders
WHERE is_available = true
  AND ST_DWithin(
        current_location,
        ST_SetSRID(ST_MakePoint($2::float8, $3::float8), 4326)::geography,
        $4::float8
      )
ORDER BY distance_meters ASC
LIMIT $1
`

type ListAvailableRidersNearbyParams struct {
	Limit        int32   `json:"limit"`
	Lng          float64 `json:"lng"`
	Lat          float64 `json:"lat"`
	RadiusMeters float64 `json:"radius_meters"`
}

type ListAvailableRidersNearbyRow struct {
	UserID         uuid.UUID   `json:"user_id"`
	Status         RiderStatus `json:"status"`
	IsAvailable    bool        `json:"is_available"`
	AssignedArea   *string     `json:"assigned_area"`
	Lat            interface{} `json:"lat"`
	Lng            interface{} `json:"lng"`
	DistanceMeters interface{} `json:"distance_meters"`
}

func (q *Queries) ListAvailableRidersNearby(ctx context.Context, arg ListAvailableRidersNearbyParams) ([]ListAvailableRidersNearbyRow, error) {
	rows, err := q.db.Query(ctx, listAvailableRidersNearby,
		arg.Limit,
		arg.Lng,
		arg.Lat,
		arg.RadiusMeters,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableRidersNearbyRow
	for rows.Next() {
		var i ListAvailableRidersNearbyRow
		if err := rows.Scan(
			&i.UserID,
			&i.Status,
			&i.IsAvailable,
			&i.AssignedArea,
			&i.Lat,
			&i.Lng,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceTokensByUser = `-- name: ListDeviceTokensByUser :many
SELECT id, user_id, token, platform, created_at FROM fcm_device_tokens
WHERE user_id = $1
`

func (q *Queries) ListDeviceTokensByUser(ctx context.Context, userID uuid.UUID) ([]FcmDeviceToken, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FcmDeviceToken
	for rows.Next() {
		var i FcmDeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, user_id, type, title, description, image_url, is_read, created_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, phone, status, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByRole = `-- name: ListUsersByRole :many
SELECT u.id, u.email, u.phone, u.status, u.created_at, u.updated_at, u.deleted_at
FROM users u
JOIN user_roles r ON r.user_id = u.id
WHERE r.role = $1 AND u.deleted_at IS NULL
ORDER BY u.created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersByRoleParams struct {
	Role   AppRole `json:"role"`
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
}

func (q *Queries) ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByRole, arg.Role, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET is_read = true
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET is_read = true
WHERE id = $1 AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}

const setUserRole = `-- name: SetUserRole :one
INSERT INTO user_roles (user_id, role)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET
    role = EXCLUDED.role
RETURNING user_id, role
`

type SetUserRoleParams struct {
	UserID uuid.UUID `json:"user_id"`
	Role   AppRole   `json:"role"`
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, setUserRole, arg.UserID, arg.Role)
	var i UserRole
	err := row.Scan(&i.UserID, &i.Role)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET status = 'deleted', deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateRiderLocation = `-- name: UpdateRiderLocation :exec
UPDATE riders
SET
    current_location = ST_SetSRID(ST_MakePoint($2::float8, $3::float8), 4326)::geography,
    updated_at = now()
WHERE user_id = $1
`

type UpdateRiderLocationParams struct {
	UserID uuid.UUID `json:"user_id"`
	Lng    float64   `json:"lng"`
	Lat    float64   `json:"lat"`
}

func (q *Queries) UpdateRiderLocation(ctx context.Context, arg UpdateRiderLocationParams) error {
	_, err := q.db.Exec(ctx, updateRiderLocation, arg.UserID, arg.Lng, arg.Lat)
	return err
}

const updateUserPhone = `-- name: UpdateUserPhone :one
UPDATE users
SET phone = $2
WHERE id = $1
RETURNING id, email, phone, status, created_at, updated_at, deleted_at
`

type UpdateUserPhoneParams struct {
	ID    uuid.UUID `json:"id"`
	Phone *string   `json:"phone"`
}

func (q *Queries) UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPhone, arg.ID, arg.Phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status = $2
WHERE id = $1
RETURNING id, email, phone, status, created_at, updated_at, deleted_at
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID  `json:"id"`
	Status UserStatus `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertFCMDeviceToken = `-- name: UpsertFCMDeviceToken :one

INSERT INTO fcm_device_tokens (user_id, token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE SET
    user_id  = EXCLUDED.user_id,
    platform = EXCLUDED.platform
RETURNING id, user_id, token, platform, created_at
`

type UpsertFCMDeviceTokenParams struct {
	UserID   uuid.UUID      `json:"user_id"`
	Token    string         `json:"token"`
	Platform DevicePlatform `json:"platform"`
}

// =============================================================================
// FCM DEVICE TOKENS (1:many with users)
// =============================================================================
func (q *Queries) UpsertFCMDeviceToken(ctx context.Context, arg UpsertFCMDeviceTokenParams) (FcmDeviceToken, error) {
	row := q.db.QueryRow(ctx, upsertFCMDeviceToken, arg.UserID, arg.Token, arg.Platform)
	var i FcmDeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.CreatedAt,
	)
	return i, err
}

const upsertRider = `-- name: UpsertRider :one
INSERT INTO riders (user_id, status, is_available, assigned_area, current_location)
VALUES (
    $1, $2, $3, $4,
    ST_SetSRID(ST_MakePoint($5::float8, $6::float8), 4326)::geography
)
ON CONFLICT (user_id) DO UPDATE SET
    status           = EXCLUDED.status,
    is_available     = EXCLUDED.is_available,
    assigned_area    = EXCLUDED.assigned_area,
    current_location = EXCLUDED.current_location,
    updated_at       = now()
RETURNING
    user_id, status, is_available, assigned_area,
    ST_Y(current_location::geometry) AS lat,
    ST_X(current_location::geometry) AS lng,
    updated_at
`

type UpsertRiderParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	Status       RiderStatus `json:"status"`
	IsAvailable  bool        `json:"is_available"`
	AssignedArea *string     `json:"assigned_area"`
	Lng          float64     `json:"lng"`
	Lat          float64     `json:"lat"`
}

type UpsertRiderRow struct {
	UserID       uuid.UUID          `json:"user_id"`
	Status       RiderStatus        `json:"status"`
	IsAvailable  bool               `json:"is_available"`
	AssignedArea *string            `json:"assigned_area"`
	Lat          interface{}        `json:"lat"`
	Lng          interface{}        `json:"lng"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertRider(ctx context.Context, arg UpsertRiderParams) (UpsertRiderRow, error) {
	row := q.db.QueryRow(ctx, upsertRider,
		arg.UserID,
		arg.Status,
		arg.IsAvailable,
		arg.AssignedArea,
		arg.Lng,
		arg.Lat,
	)
	var i UpsertRiderRow
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.IsAvailable,
		&i.AssignedArea,
		&i.Lat,
		&i.Lng,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserProfile = `-- name: UpsertUserProfile :one
INSERT INTO user_profiles (user_id, first_name, last_name, profile_image_url, birth_date)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET
    first_name        = EXCLUDED.first_name,
    last_name         = EXCLUDED.last_name,
    profile_image_url = EXCLUDED.profile_image_url,
    birth_date        = EXCLUDED.birth_date,
    updated_at        = now()
RETURNING user_id, first_name, last_name, profile_image_url, birth_date, created_at, updated_at
`

type UpsertUserProfileParams struct {
	UserID          uuid.UUID   `json:"user_id"`
	FirstName       *string     `json:"first_name"`
	LastName        *string     `json:"last_name"`
	ProfileImageUrl *string     `json:"profile_image_url"`
	BirthDate       pgtype.Date `json:"birth_date"`
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, upsertUserProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.ProfileImageUrl,
		arg.BirthDate,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.ProfileImageUrl,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
